### PR TITLE
Exclude pattern

### PR DESCRIPTION
**Pull request by ozangunalp**
Implementation of the part 1 of exclude pattern option mentioned in #14. 

The option can be given in command line via,
`git octopus -e features/feat1 -e octopus-* -s 4`
or defined in git config 
`git config octopus.excludePattern features/feat1`
`git config --add octopus.excludePattern octopus-*`

The command line option overrides the git config.

---

This change is [Reviewable](https://reviewable.io/reviews/lesfurets/git-octopus/19)

### CODE REVIEW

**Comment by apflieger** [comment]
Waow you wrote a test. It's been a while since I haven't run them. Does it still actually work?

**Comment by ozangunalp** [comment]
Well they still do work if you have access to docker base images. There is a failing test about saving conflict resolutions though. I left it as is.

**Comment by apflieger** [comment]
I tried it on OSX, seems to work well.

I guess that you changed the doc files by hand ? what's in `doc/` is actually generated based on files in `src/doc/`. Don't worry about updating generated files, I'll do it before the next release but put your changes in the sources.

**Comment by ozangunalp** [comment]
my bad, thought I was editing `src/doc`. I'll transfer changes to the src file.

**Pull request merged**
