### PR TITLE
Performance improvement on cat-UU-conflict

### PR DESCRIPTION
**Pull request by benba**
git-conflict is really awesome, but on file that has too many lines (I first noticed the issue on a 500 line file) it's very slow (at least on windows, I didn't test on Linux but I suspect this is less problematic on this plateform).
The reason is that on Windows the while loop in cat-UU-conflict si calling 3 grep per loop: this spawn 3 bash.exe and then grep.exe and this seems to be very slow.
At first I wanted to try an different approach in one pass (with awk or perl for exemple), but then I realized than just by using bash "start with" operator improve drastically the time to complete the command.

Please find below some time differences on a 2000 line demo file (project is here https://github.com/benba/conflict-perf-demo and the recorded conflict is in refs/conflicts/2b2273b9ff812101ee21db6094fefa854d95cf04):
### Without a recorded conflict (before) - 1m21.361s:

`$ git reset --hard && time git octopus -n feature*`

```
HEAD is now at 8ee0da3 Init
Branches beeing merged :
        refs/heads/feature1
        refs/heads/feature2
        refs/heads/feature3
        refs/heads/feature4
-----------------------------------------------------------
Fast-forwarding to: refs/heads/feature1
Trying simple merge with refs/heads/feature2
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
Trying simple merge with refs/heads/feature3
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
ERROR: content conflict in README.txt
fatal: merge program failed
Automated merge did not work.
Should not be doing an Octopus.
-----------------------------------------------------------
...
-----------------------------------------------------------
No conflicts found between octopus and the rest of the branches
OCTOPUS FAILED

real    1m21.361s
user    0m0.000s
sys     0m0.000s
```
### Without a recorded conflict (after) - 0m3.038s:

`$ git reset --hard && time git octopus -n feature*`

```
HEAD is now at 8ee0da3 Init
Branches beeing merged :
        refs/heads/feature1
        refs/heads/feature2
        refs/heads/feature3
        refs/heads/feature4
-----------------------------------------------------------
Fast-forwarding to: refs/heads/feature1
Trying simple merge with refs/heads/feature2
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
Trying simple merge with refs/heads/feature3
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
ERROR: content conflict in README.txt
fatal: merge program failed
Automated merge did not work.
Should not be doing an Octopus.
-----------------------------------------------------------
...
-----------------------------------------------------------
No conflicts found between octopus and the rest of the branches
OCTOPUS FAILED

real    0m3.038s
user    0m0.000s
sys     0m0.015s
```
### With a recorded conflict (before) - 3m59.042s:

`$ git reset --hard && time git octopus -n feature*`

```
HEAD is now at 8ee0da3 Init
Branches beeing merged :
        refs/heads/feature1
        refs/heads/feature2
        refs/heads/feature3
        refs/heads/feature4
-----------------------------------------------------------
Fast-forwarding to: refs/heads/feature1
Trying simple merge with refs/heads/feature2
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
Trying simple merge with refs/heads/feature3
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
ERROR: content conflict in README.txt
fatal: merge program failed
Applying conflict resolution 2b2273b9ff812101ee21db6094fefa854d95cf04
Trying simple merge with refs/heads/feature4
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
-----------------------------------------------------------
OCTOPUS SUCCESS

real    3m59.042s
user    0m0.000s
sys     0m0.031s
```
### With a recorded conflict (after) - 0m3.262s:

`$ git reset --hard && time git octopus -n feature*`

```
HEAD is now at 8ee0da3 Init
Branches beeing merged :
        refs/heads/feature1
        refs/heads/feature2
        refs/heads/feature3
        refs/heads/feature4
-----------------------------------------------------------
Fast-forwarding to: refs/heads/feature1
Trying simple merge with refs/heads/feature2
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
Trying simple merge with refs/heads/feature3
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
ERROR: content conflict in README.txt
fatal: merge program failed
Applying conflict resolution 2b2273b9ff812101ee21db6094fefa854d95cf04
Trying simple merge with refs/heads/feature4
Simple merge did not work, trying automatic merge.
Auto-merging README.txt
-----------------------------------------------------------
OCTOPUS SUCCESS

real    0m3.262s
user    0m0.000s
sys     0m0.015s
```

---

This change is [Reviewable](https://reviewable.io/reviews/lesfurets/git-octopus/15)

### CODE REVIEW

**Comment by apflieger** [comment]
Do you use it on windows then ? Do you run it on Cygwin or in the msysgit embeded bash ?

**Comment by benba** [comment]
Yes don't have the choice at work.
I use msysgit  through the official client. 

Benjamin
Envoyé de mon iPhone

**Comment by apflieger** [comment]
That's nice because we already had windows users but no contributors and I don't use windows myself.
Great work, again. I'll test it on OSX and some unix as soon as possible. I am a bit defensive regarding bash portability because I already had some troubles in the past.

**Comment by apflieger** [comment]
I tested it on OSX, the performance improvement is huge too.
I don't have any linux, let's assumes it works ;)

**Comment by mathieubolla** [comment]
Hi,

We now have two major improvements, and last release is two month old: Let's release?

Eager to release those on Homebrew...

Mathieu

**Comment by apflieger** [comment]
Here it is https://github.com/lesfurets/git-octopus/releases/tag/v1.3

2016-07-25 22:29 GMT+02:00 Mathieu Bolla notifications@github.com:

**Pull request merged**
