### PR TITLE
Enhanced signal cleaning

### PR DESCRIPTION
**Pull request by geofberard**
- We clean the repository only if we now it is clean (we don't want to reset the worspace while handling signals if it has unstaged changes when running git-octopus)
- When the automatic conflic resolution is used, the cleaning done when handling signals is not complete. Once the clean is done, the worspace is in the following state:
  $ git status
  On branch brahcn_test
  Untracked files:
  (use "git add <file>..." to include in what will be committed)
  
    .merge_file_7cDsQc
    .merge_file_C2reWa
    .merge_file_KgLfZO
    .merge_file_Zmfz3c
    .merge_file_hnrfMH

nothing added to commit but untracked files present (use "git add" to track)

### CODE REVIEW

**Comment by apflieger** [comment]
Nice catch for the first point :)
There's a problem : the current clean check

```
if [[ -n "$(git diff-index HEAD)" ]]
```

Doesn't fail for untracked files. Actually, git-octopus supports running with untracked files with no risks loosing them because there was no git-clean anywhere. But since git-conflict integration, it becomes too complicated to support this. So let's find a way to check for untracked files as well and prevent git-octopus to run

**Comment by sebastianopilla** [comment]
To check for untracked files you can use `git status --porcelain`: the result will be empty if there are no untracked files. For example:

```
# Check that the git repository is "clean", i.e. no uncommitted files
function is_git_clean () {
  WP_DIR="${1}"

  # the result of "git status --porcelain" will be empty if there are no uncommitted files
  if [ -z "$(cd ${WP_DIR} && git status --porcelain)" ]; then
    return 0
  else
    return 1
  fi
}
```

**Comment by geofberard** [comment]
Well spotted !
I amended my commit with this.

**Comment by apflieger** [comment]
The check seems a bit complicated. Something like this should do the job

```
[[ -z $(git status --porcelain) ]] || die "The repository has to be clean"
```

I had to change `-n` to `-z` i don't know why, so it has to be tested on windows at least. I checked ubuntu and OSX

**Comment by geofberard** [comment]
That is true, it's shorter and easier to read.
I'll check on windows.

I think you had to change because the statement after "||" is executed when expression return is 1 while the then clause is executed when expression return is 0

**Comment by apflieger** [comment]
I amended your commit to inline the `resetRepository` function inside `signalHandler` and merged the PR

**Comment by geofberard** [comment]
I had no time to check on Windows, have you ?

**Comment by apflieger** [comment]
Yep. There are other use of these [[ -z ]] thing anyway.

**Pull request merged**
